# Dependencies
markdown:         kramdown
highlighter:      rouge


# Permalinks
permalink:        pretty

# Setup
title:            Allison Yi Hsiang
tagline:          'Computational evolutionary paleobiologist'
description:      'Computational evolutionary paleobiologist'
baseurl:          ""
